version: "3.8"

services:
  #  Caso queira rodar MySQL via banco local em vez do container, descomente:
  #  livereload:
  #    build:
  #      context: ".."
  #      dockerfile: ./docker/golang-dev/Dockerfile
  #    container_name: container-golang
  #    image: expense-control-service
  #    environment:
  #      ENV: development
  #      DB_HOST: ${DB_HOST}
  #      DB_PORT: ${DB_PORT}
  #      DB_USER: ${DB_USERNAME}
  #      DB_PASS: ${DB_PASSWORD}
  #      DB_NAME: ${DB_NAME}
  #    extra_hosts:
  #      - "host.docker.internal:host-gateway"
  #    ports:
  #      - "9000:9000"
  #      - "40000:40000"
  #    volumes:
  #      - ../:/app
  #    networks:
  #      - service-go

  mysqldb:
    image: mysql:8.0
    container_name: finance_db
    environment:
      MYSQL_DATABASE: expense-control-service
      MYSQL_USER: everson.bueno
      MYSQL_PASSWORD: Teste@1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - service-go

  migrate:
    image: migrate/migrate
    command:
      [
          "-path", "/migrations",
          "-database mysql://everson.bueno:Teste%401234@tcp(mysqldb:3307)/expense-control-service?multiStatements=true",
          "up"
      ]
    volumes:
      - ./internal/database/migrations:/migrations
    depends_on:
      - mysqldb
    networks:
      - service-go

networks:
  service-go:
    driver: bridge

volumes:
  mysql_data:
