version: "3.4"

services:
  livereload:
    build:
      context: ".."
      dockerfile: ./docker/golang-dev/Dockerfile
    container_name: container-golang
    image: expense-control-service
    environment:
      ENV: development
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"
      - "40000:40000"
    volumes:
      - ../:/app
    networks:
      - service-go

  # Caso queira rodar MySQL via container em vez do banco local, descomente:
  # mysqldb:
  #   image: mysql:5.7
  #   platform: linux/arm64
  #   container_name: container-mysql
  #   environment:
  #     MYSQL_DATABASE: expense-control-service
  #     MYSQL_USER: everson.bueno
  #     MYSQL_PASSWORD: Teste@1234
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - service-go

networks:
  service-go:
    driver: bridge

volumes:
  mysql_data:
