version: "3.8"

services:
  livereload:
    build:
      context: ".."
      dockerfile: ./docker/golang-dev/Dockerfile
    container_name: container-golang
    image: expense-control-service
    environment:
      ENV: development
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USERNAME: everson.bueno
      DB_PASSWORD: Teste@1234
      DB_NAME: expense-control-service
    # extra_hosts:
    # - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"
      - "40000:40000"
    volumes:
      - ../:/app
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - service-go

  mysqldb:
    image: mysql:8.0
    container_name: finance_db
    environment:
      MYSQL_DATABASE: expense-control-service
      MYSQL_USER: everson.bueno
      MYSQL_PASSWORD: Teste@1234
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - service-go
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "everson.bueno", "-pTeste@1234"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  migrate:
    image: migrate/migrate
    command:
      [
          "-path", "/migrations",
          "-database", "mysql://everson.bueno:Teste%401234@tcp(mysqldb:3306)/expense-control-service?multiStatements=true",
          "up"
      ]
    volumes:
      - ../internal/database/migrations:/migrations
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - service-go

networks:
  service-go:
    driver: bridge

volumes:
  mysql_data:
